steps:
  - name: ":classical_building: Building docker image"
    command: "docker build -f Dockerfile.dev . -t pratikbhumkar/invoicer-app"
  - wait
  - name: ":lint-roller: Checking for lints"
    command: "docker run pratikbhumkar/invoicer-app npm run lint"
  - wait
  - name: ":lint-roller: Testing code"
    command: "docker run pratikbhumkar/invoicer-app npm test"
  - block: ":rocket: Run local build!"
  - name: ":classical_building: Building local image"
    command: "docker build -f Dockerfile . -t pratikbhumkar/invoicer-app"
  - wait
  - name: ":surfer: Running local image"
    command: "docker run -p 3000:3000 -d pratikbhumkar/invoicer-app"
